//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BL_HEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BL_HEAD()
        {
            this.BL_ITEM = new HashSet<BL_ITEM>();
        }
    
        public int BL_HEADID { get; set; }
        public int MANIFESTID { get; set; }
        public string BL_NUMBER { get; set; }
        public Nullable<int> TRAFFICID { get; set; }
        public Nullable<bool> BL_CONT { get; set; }
        public string BL_TYPE { get; set; }
        public string CSGNEE_NAM { get; set; }
        public string CSGNEE_ADD { get; set; }
        public string CSGNEE_POSTALCODE { get; set; }
        public Nullable<int> CSGNEE_CITY { get; set; }
        public string CSGNEE_FAX { get; set; }
        public string CSGNEE_EMAIL { get; set; }
        public string CSGNOR_NAM { get; set; }
        public string CSGNOR_ADD { get; set; }
        public string CSGNOR_POSTALCODE { get; set; }
        public Nullable<int> CSGNOR_CITY { get; set; }
        public string CSGNOR_FAX { get; set; }
        public string CSGNOR_EMAIL { get; set; }
        public string NOTIFY_NAM { get; set; }
        public string NOTIFY_ADD { get; set; }
        public string NOTIFY_POSTALCODE { get; set; }
        public Nullable<int> NOTIFY_CITY { get; set; }
        public string NOTIFY_FAX { get; set; }
        public string NOTIFY_EMAIL { get; set; }
        public Nullable<int> CONSIGNEEID { get; set; }
        public Nullable<int> PL_LOADING { get; set; }
        public Nullable<int> PL_DISCHAR { get; set; }
        public Nullable<int> PL_DESTINA { get; set; }
        public Nullable<int> GOODS_ORIG { get; set; }
        public Nullable<int> FORWARDERID { get; set; }
        public Nullable<int> CLEARERID { get; set; }
        public Nullable<int> OPERATORID { get; set; }
        public Nullable<int> TERMINALID { get; set; }
        public string STOP_STATUS { get; set; }
        public Nullable<System.DateTime> STOP_DATE { get; set; }
        public Nullable<int> STOP_USERID { get; set; }
        public Nullable<int> STOP_MOTIVEID { get; set; }
        public string STOP_COMMENTS { get; set; }
        public Nullable<System.DateTime> DISCHARGED { get; set; }
        public System.DateTime CREADATE { get; set; }
        public System.DateTime UPDADATE { get; set; }
        public int UID_USES { get; set; }
        public byte[] VER_N { get; set; }
        public Nullable<bool> FREE_ZONE { get; set; }
    
        public virtual MANIFEST MANIFEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BL_ITEM> BL_ITEM { get; set; }
    }
}
