//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BL_ITEM
    {
        public int BL_ITEMID { get; set; }
        public int BL_HEADID { get; set; }
        public int ITEM_NB { get; set; }
        public string CUSTOMCLRNB { get; set; }
        public Nullable<int> CUSTOM_HEADID { get; set; }
        public Nullable<int> CUSTOM_ITEMID { get; set; }
        public string GOODS_DESC { get; set; }
        public Nullable<decimal> NET_WEIGHT { get; set; }
        public Nullable<decimal> GRS_WEIGHT { get; set; }
        public Nullable<int> VOLUME { get; set; }
        public Nullable<int> PACK_CODEID { get; set; }
        public Nullable<int> PACK_NB { get; set; }
        public Nullable<int> COMMODITYID { get; set; }
        public Nullable<int> DG_CLASSID { get; set; }
        public Nullable<int> CARGO_TYPEID { get; set; }
        public string SHIP_MK { get; set; }
        public Nullable<System.DateTime> CUSTOMCLRDATE { get; set; }
        public string CUSTOMNB { get; set; }
        public Nullable<int> SERIALNB { get; set; }
        public Nullable<bool> FREE_ZONE { get; set; }
        public string UNDG_CODE { get; set; }
        public Nullable<int> UID_USES { get; set; }
        public byte[] VER_N { get; set; }
        public Nullable<System.DateTime> CREADATE { get; set; }
        public Nullable<System.DateTime> UPDADATE { get; set; }
        public string Tag { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> Date_Stop { get; set; }
        public string Desc_Stop { get; set; }
    
        public virtual BL_HEAD BL_HEAD { get; set; }
    }
}
