//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.MANIFEST = new HashSet<MANIFEST>();
        }
    
        public int BOOKINGID { get; set; }
        public string BOOKING1 { get; set; }
        public int VESSELID { get; set; }
        public string BOOKINGTYP { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> SUBM_DATE { get; set; }
        public Nullable<int> SHIPAGENTID { get; set; }
        public Nullable<int> CHARTAGENTID { get; set; }
        public Nullable<int> SH_LINEID { get; set; }
        public Nullable<System.DateTime> ETA_DATE { get; set; }
        public Nullable<System.DateTime> ETD_DATE { get; set; }
        public Nullable<decimal> DRAFT_IN { get; set; }
        public Nullable<decimal> DRAFT_OUT { get; set; }
        public Nullable<int> NEXT_PORTID { get; set; }
        public Nullable<int> LAST_PORTID { get; set; }
        public Nullable<int> COMMODITYID { get; set; }
        public Nullable<decimal> D_LIQBULK { get; set; }
        public Nullable<decimal> L_LIQBULK { get; set; }
        public Nullable<decimal> D_DRYBULK { get; set; }
        public Nullable<decimal> L_DRYBULK { get; set; }
        public Nullable<decimal> D_GALCARGO { get; set; }
        public Nullable<decimal> L_GALCARGO { get; set; }
        public Nullable<short> D_20NB_E { get; set; }
        public Nullable<short> D_20NB_F { get; set; }
        public Nullable<short> L_20NB_E { get; set; }
        public Nullable<short> L_20NB_F { get; set; }
        public Nullable<decimal> D_20TN_E { get; set; }
        public Nullable<decimal> D_20TN_F { get; set; }
        public Nullable<decimal> L_20TN_E { get; set; }
        public Nullable<decimal> L_20TN_F { get; set; }
        public Nullable<short> D_40NB_E { get; set; }
        public Nullable<short> D_40NB_F { get; set; }
        public Nullable<short> L_40NB_E { get; set; }
        public Nullable<short> L_40NB_F { get; set; }
        public Nullable<decimal> D_40TN_E { get; set; }
        public Nullable<decimal> D_40TN_F { get; set; }
        public Nullable<decimal> L_40TN_E { get; set; }
        public Nullable<decimal> L_40TN_F { get; set; }
        public Nullable<short> D_VEHNB { get; set; }
        public Nullable<short> L_VEHNB { get; set; }
        public Nullable<decimal> D_VEHTN { get; set; }
        public Nullable<decimal> L_VEHTN { get; set; }
        public Nullable<short> D_LIVNB { get; set; }
        public Nullable<short> L_LIVNB { get; set; }
        public Nullable<decimal> D_LIVTN { get; set; }
        public Nullable<decimal> L_LIVTN { get; set; }
        public Nullable<short> D_HVLNB { get; set; }
        public Nullable<short> L_HVLNB { get; set; }
        public Nullable<decimal> D_HVLMAXTN { get; set; }
        public Nullable<decimal> L_HVLMAXTN { get; set; }
        public Nullable<short> D_GANGS { get; set; }
        public Nullable<short> L_GANGS { get; set; }
        public Nullable<short> D_HOOKS { get; set; }
        public Nullable<short> L_HOOKS { get; set; }
        public Nullable<bool> CONT_FULL { get; set; }
        public Nullable<bool> CONT_GEAR { get; set; }
        public string RORORAMP { get; set; }
        public string RORONEED { get; set; }
        public string VOYAGE_A { get; set; }
        public string VOYAGE_D { get; set; }
        public int UID_USES { get; set; }
        public byte[] VER_N { get; set; }
        public System.DateTime CREADATE { get; set; }
        public System.DateTime UPDADATE { get; set; }
        public Nullable<int> CARGO_TYPEID { get; set; }
        public Nullable<bool> HANDLING_DIRECT { get; set; }
        public Nullable<bool> HANDLING_INDIRECT { get; set; }
        public Nullable<System.DateTime> ISSC_DATE { get; set; }
        public string ISSC_NB { get; set; }
        public Nullable<int> ARVTYPEID { get; set; }
        public Nullable<bool> ONECARGOCONSIGNEE { get; set; }
        public Nullable<int> CONSIGNEEID { get; set; }
        public Nullable<int> CONTDISCHARGEID { get; set; }
        public Nullable<int> CONTTALLYID { get; set; }
        public Nullable<int> PORTLOCAID { get; set; }
        public Nullable<int> BERTHSIDEID { get; set; }
        public Nullable<int> CONTDRAFTSURVEYID { get; set; }
        public Nullable<int> TALLYID { get; set; }
        public Nullable<int> VESSEL2ID { get; set; }
    
        public virtual VESSELS VESSELS { get; set; }
        public virtual SH_AGENT SHIPAGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANIFEST> MANIFEST { get; set; }
    }
}
