//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCOMSEntities : DbContext
    {
        public GCOMSEntities()
            : base("name=GCOMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKING> BOOKING { get; set; }
        public virtual DbSet<SH_AGENT> SH_AGENT { get; set; }
        public virtual DbSet<VESSELS> VESSELS { get; set; }
        public virtual DbSet<STORREBL> STORREBL { get; set; }
        public virtual DbSet<BL_HEAD> BL_HEAD { get; set; }
        public virtual DbSet<MANIFEST> MANIFEST { get; set; }
        public virtual DbSet<BL_ITEM> BL_ITEM { get; set; }
    }
}
