//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_AGENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SH_AGENT()
        {
            this.BOOKING = new HashSet<BOOKING>();
        }
    
        public int SHIPAGENTID { get; set; }
        public string SHIPAGENT { get; set; }
        public string LONGNAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public int UID_USES { get; set; }
        public byte[] VER_N { get; set; }
        public System.DateTime CREADATE { get; set; }
        public System.DateTime UPDADATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKING { get; set; }
    }
}
