//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORREBL
    {
        public int STORREBLID { get; set; }
        public Nullable<int> STORREBL_HeadID { get; set; }
        public Nullable<int> BL_ITEMID { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string SERIAL { get; set; }
        public Nullable<System.DateTime> DISCHARGE_DATE { get; set; }
        public Nullable<int> PACK_NB { get; set; }
        public Nullable<decimal> GRS_WEIGHT { get; set; }
        public string LCNO { get; set; }
        public string ISSUEING_BANK { get; set; }
        public string COMMENTS { get; set; }
        public string CLEARER { get; set; }
        public string PRERSTORBL_ID { get; set; }
        public string BUYER_NAME { get; set; }
        public string SALEDESC { get; set; }
        public string STATUS { get; set; }
        public byte[] PRINT_NB { get; set; }
        public byte[] VER_N { get; set; }
        public int UID_USES { get; set; }
        public System.DateTime CREADATE { get; set; }
        public System.DateTime UPDADATE { get; set; }
        public Nullable<System.DateTime> DELIVERYORDERDATE { get; set; }
        public string DELIVERYORDERNUMBER { get; set; }
        public Nullable<int> Payment { get; set; }
        public string RecepitNoOperator { get; set; }
        public string RecepitNoPort { get; set; }
        public Nullable<System.DateTime> RecepitDateOperator { get; set; }
        public Nullable<System.DateTime> RecepitDatePort { get; set; }
        public byte[] PermitForPrintReplica { get; set; }
        public Nullable<System.Guid> Print_GUID { get; set; }
        public byte[] PRINT_NB_Replica { get; set; }
        public Nullable<System.Guid> Print_ReplicaGUID { get; set; }
        public Nullable<int> PaymentOP { get; set; }
        public Nullable<int> CONSIGNEEID { get; set; }
    }
}
