//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VESSELS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VESSELS()
        {
            this.BOOKING = new HashSet<BOOKING>();
        }
    
        public int VESSELID { get; set; }
        public string LLOYD { get; set; }
        public string SHIPNAME { get; set; }
        public string FORMERNAME { get; set; }
        public string CALLSIGN { get; set; }
        public Nullable<int> PORTLLOYID { get; set; }
        public Nullable<int> SHIPOWNERID { get; set; }
        public Nullable<int> FLAGID { get; set; }
        public Nullable<int> VESSELTYPEID { get; set; }
        public Nullable<int> YEARBUILT { get; set; }
        public Nullable<decimal> LOA { get; set; }
        public Nullable<decimal> BEAM { get; set; }
        public Nullable<decimal> DRAFT { get; set; }
        public Nullable<int> GRT { get; set; }
        public Nullable<int> NRT { get; set; }
        public Nullable<int> DWT { get; set; }
        public Nullable<short> HOLDNB { get; set; }
        public Nullable<short> TANKNB { get; set; }
        public Nullable<int> TEUCAPA { get; set; }
        public Nullable<int> LINEARCAPA { get; set; }
        public string REGISTERNB { get; set; }
        public int UID_USES { get; set; }
        public byte[] VER_N { get; set; }
        public System.DateTime CREADATE { get; set; }
        public System.DateTime UPDADATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKING { get; set; }
    }
}
